### ISSUE TITLE
Does not detect spotify running 

### ISSUE THREAD

**Issue by marizzz95** [emilioastarita/lyricfier2#1]
I installed this on macOS Sierra, but when I launch the app the terminal outputs:
Failed to get metadata from Spotify The name org.mpris.MediaPlayer2.spotify was not provided by any .service files

and lyricfier asks if spotify is running.

is this caused by one of the entries in my hosts file? lyricfier1 worked with them, though.

**Comment by emilioastarita** [comment]
I've just added support for darwin in last commit. Can you try the build and give me some feedback ?
Thanks!

**Comment by marizzz95** [comment]
I have just installed the latest build and I'm happy to confirm it now works on macOS. 
It would be nice if there was some sort of line wrapping though, so you don't have to horizontally scroll the lyrics.

**Comment by emilioastarita** [comment]
Great!! :tada:
