### ISSUE TITLE
Player, please...

### ISSUE THREAD

**Issue by muezis** [emilioastarita/lyricfier2#12]
Hey, It's really good. But there is one problem. Player. Please add a player. I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

So far, your app isn't much better than just opening text on genius. But if you make a normal player that can be conveniently controlled, it will be the best that is available at the moment.

**Comment by emilioastarita** [comment]
Sorry but it's not planed to support player controls
