### ISSUE TITLE
Not Work with Spotify Latest version

### ISSUE THREAD

**Issue by zeeid** [emilioastarita/lyricfier2#14]
Please Update ,
not work with latest version of spotify

**Comment by satonotdead** [comment]
There is a workaround or similar app around there? (:

**Comment by zeeid** [comment]
@satoshinotdead yoo bro, right now i used **spicetify** . its more more recommended.
you can search in google "how to instal spicetify"

**Comment by zeeid** [comment]
use spicetify its more recommended
