### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by baymac** [emilioastarita/lyricfier2#3]
Dependencies install with `dep ensure` doesn't do anything. And there is no `cmd/` dir inside `lyricfinder2/`.

**Comment by emilioastarita** [comment]
Sorry we were moving to a client / server design cause Qt building was too much trouble for releasing in all platforms. 

For ubuntu you can check last release (0.2) and install as .deb package or build directly from sources:

https://github.com/emilioastarita/lyricfier2/releases/tag/0.2

**Comment by baymac** [comment]
Excellent. It works. What was the issue btw?
