### ISSUE TITLE
Sometimes, translated lyrics are displayed

### ISSUE THREAD

**Issue by Dagefoerde** [emilioastarita/lyricfier2#5]
Thanks for this tool! It's great on the desktop! :)

Sometimes, Lyricfier shows a translation instead of showing the original lyrics of a song. This has happened with https://open.spotify.com/track/0FwJEK5wxKMKcloPAIfGU9?si=o1rPjEWYTPaxb8wvg4N90w, where I ended up with a Brazilian translation from Genius. Reloading the browser did not help. However, when I tried to reproduce this, I got the correct result, so it only happens sometimes.

Sorry, that this might be hard to reproduce (but I tried!). This has happened with another song as well.

**Comment by Dagefoerde** [comment]
another example:

https://open.spotify.com/track/2C6WXnmZ66tHhHlnvwePiK?si=Z1siy_ppToaJUCnb85PX3Q shows up in either Spanish or Dutch.

**Comment by josico14** [comment]
Nice app mate! I use it every day, thanks for it.
This issue happens to me too.

![Screenshot from 2020-02-03 19-47-47](https://user-images.githubusercontent.com/60622934/73681167-13509480-46be-11ea-85b3-9a0879f38cca.png)

**Comment by emilioastarita** [comment]
In last version is possible to edit local files to fix these errors.
